### ISSUE TITLE
development

### ISSUE THREAD

**Issue by luisandia** [luisandia/django-store#3]
You must implement CRUD:

- [x] unit_type
- [x] operation_type
- [x] voucher_type

**Comment by luisandia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [luisandia/django-store](https://trello.com/c/jAkWCn5g/1-luisandia-django-store)

**Comment by luisandia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [luisandia/django-store](https://trello.com/c/A8ydiTXo/3-luisandia-django-store)

**Comment by SebasWilde** [comment]
Finished
